package com.mybatis.dao.mapper;

import com.mybatis.dao.pojo.MenuPo;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface MenuPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tting_org_menu
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    int deleteByPrimaryKey(Integer mainId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tting_org_menu
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    int insert(MenuPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tting_org_menu
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    MenuPo selectByPrimaryKey(Integer mainId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tting_org_menu
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    List<MenuPo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tting_org_menu
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    int updateByPrimaryKey(MenuPo record);
}