package com.mybatis.dao.mapper;

import com.mybatis.dao.pojo.UserPo;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface UserPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tting_org_user
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    int deleteByPrimaryKey(Integer mainId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tting_org_user
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    int insert(UserPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tting_org_user
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    UserPo selectByPrimaryKey(Integer mainId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tting_org_user
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    List<UserPo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tting_org_user
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    int updateByPrimaryKey(UserPo record);
}