package com.mybatis.dao.pojo;

public class MenuPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tting_org_menu.mainId
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    private Integer mainId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tting_org_menu.parentId
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tting_org_menu.menuName
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    private String menuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tting_org_menu.menuCode
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    private String menuCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tting_org_menu.menuMethod
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    private String menuMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tting_org_menu.menuUrl
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    private String menuUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tting_org_menu.orderId
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tting_org_menu.isChild
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    private Integer isChild;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tting_org_menu.isEnabled
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    private Integer isEnabled;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tting_org_menu.mainId
     *
     * @return the value of tting_org_menu.mainId
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    public Integer getMainId() {
        return mainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tting_org_menu.mainId
     *
     * @param mainId the value for tting_org_menu.mainId
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    public void setMainId(Integer mainId) {
        this.mainId = mainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tting_org_menu.parentId
     *
     * @return the value of tting_org_menu.parentId
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tting_org_menu.parentId
     *
     * @param parentId the value for tting_org_menu.parentId
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tting_org_menu.menuName
     *
     * @return the value of tting_org_menu.menuName
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tting_org_menu.menuName
     *
     * @param menuName the value for tting_org_menu.menuName
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tting_org_menu.menuCode
     *
     * @return the value of tting_org_menu.menuCode
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    public String getMenuCode() {
        return menuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tting_org_menu.menuCode
     *
     * @param menuCode the value for tting_org_menu.menuCode
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    public void setMenuCode(String menuCode) {
        this.menuCode = menuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tting_org_menu.menuMethod
     *
     * @return the value of tting_org_menu.menuMethod
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    public String getMenuMethod() {
        return menuMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tting_org_menu.menuMethod
     *
     * @param menuMethod the value for tting_org_menu.menuMethod
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    public void setMenuMethod(String menuMethod) {
        this.menuMethod = menuMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tting_org_menu.menuUrl
     *
     * @return the value of tting_org_menu.menuUrl
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    public String getMenuUrl() {
        return menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tting_org_menu.menuUrl
     *
     * @param menuUrl the value for tting_org_menu.menuUrl
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tting_org_menu.orderId
     *
     * @return the value of tting_org_menu.orderId
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tting_org_menu.orderId
     *
     * @param orderId the value for tting_org_menu.orderId
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tting_org_menu.isChild
     *
     * @return the value of tting_org_menu.isChild
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    public Integer getIsChild() {
        return isChild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tting_org_menu.isChild
     *
     * @param isChild the value for tting_org_menu.isChild
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    public void setIsChild(Integer isChild) {
        this.isChild = isChild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tting_org_menu.isEnabled
     *
     * @return the value of tting_org_menu.isEnabled
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    public Integer getIsEnabled() {
        return isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tting_org_menu.isEnabled
     *
     * @param isEnabled the value for tting_org_menu.isEnabled
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    public void setIsEnabled(Integer isEnabled) {
        this.isEnabled = isEnabled;
    }
}