package com.mybatis.dao.pojo;

public class UserPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tting_org_user.mainId
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    private Integer mainId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tting_org_user.openId
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    private String openId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tting_org_user.name
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tting_org_user.sex
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tting_org_user.city
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tting_org_user.country
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tting_org_user.headimgUrl
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    private String headimgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tting_org_user.longitude
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    private String longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tting_org_user.latitude
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    private String latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tting_org_user.isFollow
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    private Integer isFollow;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tting_org_user.mainId
     *
     * @return the value of tting_org_user.mainId
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    public Integer getMainId() {
        return mainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tting_org_user.mainId
     *
     * @param mainId the value for tting_org_user.mainId
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    public void setMainId(Integer mainId) {
        this.mainId = mainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tting_org_user.openId
     *
     * @return the value of tting_org_user.openId
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tting_org_user.openId
     *
     * @param openId the value for tting_org_user.openId
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    public void setOpenId(String openId) {
        this.openId = openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tting_org_user.name
     *
     * @return the value of tting_org_user.name
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tting_org_user.name
     *
     * @param name the value for tting_org_user.name
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tting_org_user.sex
     *
     * @return the value of tting_org_user.sex
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tting_org_user.sex
     *
     * @param sex the value for tting_org_user.sex
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tting_org_user.city
     *
     * @return the value of tting_org_user.city
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tting_org_user.city
     *
     * @param city the value for tting_org_user.city
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tting_org_user.country
     *
     * @return the value of tting_org_user.country
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tting_org_user.country
     *
     * @param country the value for tting_org_user.country
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tting_org_user.headimgUrl
     *
     * @return the value of tting_org_user.headimgUrl
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    public String getHeadimgUrl() {
        return headimgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tting_org_user.headimgUrl
     *
     * @param headimgUrl the value for tting_org_user.headimgUrl
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    public void setHeadimgUrl(String headimgUrl) {
        this.headimgUrl = headimgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tting_org_user.longitude
     *
     * @return the value of tting_org_user.longitude
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tting_org_user.longitude
     *
     * @param longitude the value for tting_org_user.longitude
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tting_org_user.latitude
     *
     * @return the value of tting_org_user.latitude
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tting_org_user.latitude
     *
     * @param latitude the value for tting_org_user.latitude
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tting_org_user.isFollow
     *
     * @return the value of tting_org_user.isFollow
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    public Integer getIsFollow() {
        return isFollow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tting_org_user.isFollow
     *
     * @param isFollow the value for tting_org_user.isFollow
     *
     * @mbg.generated Wed Aug 26 16:05:34 CST 2020
     */
    public void setIsFollow(Integer isFollow) {
        this.isFollow = isFollow;
    }
}